### ISSUE TITLE
IllegalBlockSizeException when attempting to encrypt multiple files in a loop

### ISSUE THREAD

**Issue by raytonnz** [snatik/android-storage#37]
I am trying to encrypt multiple .txt files which will be encrypted over a for-loop iteration. The list of files are stored in a String[] array. The individual .txt files are able to be encrypted without the loop iteration, and the error occurs when attempting to encrypt multiple files. Here is a snippet of my code:

                    String[] filenames = getFilenames(selectedFiles);

                    for(int fileNum = 0; fileNum<filenames.length;fileNum++){

                        //Read currently working text file
                        String content = storage.readTextFile(extPath+"/"+storedName+"/"+filenames[fileNum]+".txt");
                        System.out.println(" READING FILE FROM ["+fileNum+"] : "+extPath+"/"+storedName+"/"+filenames[fileNum]);

                        //Encrypt file
                        storage.setEncryptConfiguration(configuration);
                        storage.createFile(extPath+"/"+storedName+"/"+filenames[fileNum], content);

                        System.out.println("INFO : FILE ENCRYPTED");

                    }

The first file in the Array filenames will be encrypted, but fails upon hitting the 2nd file.

Just my guess, but could it have something to do with the the buffer not flushing?

**Comment by sromku** [comment]
You are right. Just debugged your example and found the issue. First of all, much thanks for providing the snippet and explanation, it helps a lot.

The reason is that you try decrypting unencrypted file. And it happens because we `setEncryptConfiguration` and leave it as is. When second loop iteration happens, the configuration is still exists. When `readTextFile` happens it tries to decrypt the content of the file and here we fail. The content of the second file isn't encrypted but we try to decrypt it.

To fix this, just nullify the configuration before reading the content of unencrypted files -  `storage.setEncryptConfiguration(null)`. After that, set the configuration every time you create the file as you did. So the full working code in your case would be:

```java
String[] filenames = getFilenames(selectedFiles);
for(int fileNum = 0; fileNum<filenames.length;fileNum++){

    //Read currently working text file
    storage.setEncryptConfiguration(null); // <--- the fix ---
    String content = storage.readTextFile(extPath+"/"+storedName+"/"+filenames[fileNum]+".txt");
    System.out.println(" READING FILE FROM ["+fileNum+"] : "+extPath+"/"+storedName+"/"+filenames[fileNum]);

    //Encrypt file
    storage.setEncryptConfiguration(configuration);
    storage.createFile(extPath+"/"+storedName+"/"+filenames[fileNum], content);

    System.out.println("INFO : FILE ENCRYPTED");
}
```

Hope it helps ;)

**Comment by raytonnz** [comment]
That solved the problem perfectly, thanks sromku!

**Comment by sromku** [comment]
Great 👍
